### ISSUE TITLE
Ledger Live in multiple languages

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-desktop#1044]
- [x] I have checked this feature was not yet requested.

I think people would like to see Ledger Live in more languages.
Languages like: French, German, Spanish, Dutch, Italian.

It would be great to use a website like Transifex (or something else) where the community can help translating Ledger Live.

#### Part of the application

Overall application

**Comment by meriadec** [comment]
Hello, we agree, and this is even already prepared, and in the plan :wink:
The whole app is translated, using [crowdin](https://crowdin.com/project/ledger-wallet), and for the moment only English is supported.

**Comment by gre** [comment]
totally. We can't open the translated yet until we have
- [ ] established the final list of wording of the app
- [ ] remove the duplicates because there are a lot
- [ ] remove the unused because there are a lot

once that, we should be close to open this (but we also need to organize it properly with our other teams).

Thanks for your patience

**Comment by bfilipek** [comment]
Could it be possible to add Polish language on [crowdin](https://crowdin.com/project/ledger-wallet)?
I can help with translation to Polish :smirk:

**Comment by ivan93sd** [comment]
Can we add Serbian (Latin) to the list of languages for translation? Thanks.

**Comment by gre** [comment]
https://crowdin.com/translate/ledger-wallet
