### ISSUE TITLE
Please implement login authentication process with DigiID

### ISSUE THREAD

**Issue by k010c1232** [LedgerHQ/ledger-live-desktop#1048]
- [x] I have checked this feature was not yet requested.

I forgot my password sometime. At that time, I don't remember my password. I've one suggestion for Ledger live's login process. Will you implement DigiID login authentication tech? 
https://www.digi-id.io/ 

#### Part of the application
Login Process

**Comment by gre** [comment]
- The password is optional and not recoverable
- We don't save it anywhere because it's just use to encrypt and decrypt your data. like a passphrase in PGP
- The password only protect someone to access your data on your computer. but these data can fully be restored with your device, trashing them completely and restoring the same data again is possible. (only the custom name you might have given to your accounts are lost)

we're not planning to save it somewhere else as it would weaken its purpose.
