### ISSUE TITLE
Bitcoin bech32 addresses

### ISSUE THREAD

**Issue by bfilipek** [LedgerHQ/ledger-live-desktop#1051]
The application should supports BTC bech32 addresses.

More information:
https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

**Comment by bfilipek** [comment]
Any ETA for this feature?

Bech32 is already used in Ledger + Electrum wallet. 
I would be great if Ledger Live had bech32 support 😉

**Comment by kirillkovalenko** [comment]
This issue is second most liked after #1025 and yet there seems to be a silence from the development team. I also checked [trello](https://trello.com/b/5nQ1mdzt/ledger-overview-internal-and-external-developments?menu=filter&filter=bech32) and see nothing there as well. @EricLarch could you pleas elaborate the current status and plans for bech32 support?

**Comment by kirillkovalenko** [comment]
Apparently ordinary people can not get answers for uncomfortable questions, but high-profile bitcoiners can. So I just leave it here: https://twitter.com/LedgerHQ/status/1095971576229580800

**Comment by zeycus** [comment]
Nothing has been done, so I put some effort and found out how to use Deterministic Wallet Path Derivations to access my different Ledger accounts, using Electrum. Now Wasabi supports Ledger too, of course with native Bech32. With the additional protection of a Tor layer, not present in LedgerLive. For all this, in the end I see no reason to use LedgerLive anymore, you pushed me to make the effort of learning better technology, and for that I am thankful.

**Comment by ciconsulting** [comment]
Still outstanding with no news?

**Comment by gre** [comment]
👋  https://github.com/LedgerHQ/ledger-live-desktop/pull/2026
