### ISSUE TITLE
When changing currency, Ledger Live should choose an exchange by default

### ISSUE THREAD

**Issue by ktechmidas** [LedgerHQ/ledger-live-desktop#1138]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.0.1**
- Platform and version: **Windows 10**

#### Expected behavior

When I change currency, Ledger Live should choose a default exchange rather than leave it blank.

#### Actual behavior

When I changed from USD to HKD then closed the settings, it showed a HKD value of zero despite me having BTC in there at the time. This is because I didn't select an exchange, this seems counter intuitive to force the user to select an exchange when they may not even know they can switch exchanges. (Took me a few seconds after seeing zero to figure out it was the exchange)

Perhaps even a warning when you close settings that you haven't selected an exchange would suffice.

![image](https://user-images.githubusercontent.com/9920871/42732088-1a2cc76e-884d-11e8-806f-edbe80f082d3.png)

**Comment by gre** [comment]
Actually the app does chose an exchange for you (the one with most volume)
The issue is is more that HKD currently have no exchange available and it’s actually a problem with our current api. We are investigating

**Comment by ktechmidas** [comment]
HKD does have an exchange available (Gatecoin) and even when I switch back to USD it still shows zero unless I select the exchange again.

CNY does not have one available though....

**Comment by ktechmidas** [comment]
@gre Take a look...

![hkd1](https://user-images.githubusercontent.com/9920871/42734316-4c106fca-8874-11e8-8089-a1a639f076a6.png)
![hkd2](https://user-images.githubusercontent.com/9920871/42734317-4c3f2752-8874-11e8-8f9c-ef8e24bebad1.png)
![hkd3](https://user-images.githubusercontent.com/9920871/42734319-4c718de6-8874-11e8-923a-b3efd91524e0.png)

**Comment by ktechmidas** [comment]
It still has the BitMEX option when I select HKD... thus making it invalid and setting zero (then clearing it out if I close and reopen settings) then I go back to the settings and select Gatecoin and it's all fine.

**Comment by gre** [comment]
Ok I understand what's happening.. BitMEX used to exist for the pair but probably have no longer data since a lot of time.. so our api think it's legit to ask this and return data , yet the exchanges are not in the list.. something around this line.
I'm going to try a fix that will force reseting the exchange when you switch between fiats.

the second problem about no exchanges listed for CNY is known (and happen for a few other fiats too), & currently looking at it. It's basically related to our third party for countervalues that miss rates for some days.

**Comment by gre** [comment]
so i figured things out, there were actually 3 parts to improve:

- https://github.com/LedgerHQ/ledger-live-common/pull/52 <- we'll disable some fiat (CNY, CHF, SEK) because there is no way we can support them in short term because apparently not anymore traded in direct pair :( need review from front team & merge & then we need to bump the live-common dep. cc @meriadec 
- https://github.com/LedgerHQ/ledger-api-countervalue/pull/9 <- there were a bug in the "fallback exchange" that is used. this is actually the main reason of the present bug. we need to deploy a new version of this api. cc @fdv 
- https://github.com/LedgerHQ/ledger-live-desktop/pull/1143 <- we know force a refresh when you switch fiat. it's better to do so because it's preferable to fallback on the "first choice" that is always ordered to be the one with most volume. just a PR in here. this one is minor btw, but still important subtility

**Comment by gre** [comment]
😅
