### ISSUE TITLE
Sorting order is not updated after importing accounts

### ISSUE THREAD

**Issue by EricLarch** [LedgerHQ/ledger-live-desktop#1153]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.0.2**
- Platform and version: **Mac 10.13.5**

#### Expected behavior

Account imported should automatically be sorted by the selected preference.

#### Actual behavior

Accounts are imported in the order they are found, and added at the bottom of the list. Changing views doesn't trigger a reorder. The only way to sort correctly the accounts is to manually select the "sort by" option.

#### Steps to reproduce the behavior

- import accounts
- they'll be in the order of importation and not the order of balance

![image](https://user-images.githubusercontent.com/1017848/42760257-2f7d24fc-890a-11e8-8954-e5a9a67d6663.png)

**Comment by gre** [comment]
this is more a feature and tradeoff today.
It's a bit tricky for performance to always attempt to sort on the fly accounts each single time something changes (because see, the balance sort is not stable in time, it can randomly changes, make your accounts "swapping" each time countervalues reload). It's also not clear that the portfolio sort will order the accounts "globally" and I think this will be rediscussed in future if we have a "list of accounts" screen.

By default, the sort that happens is a sort by creation date, and a re-order happens only if you change the sort.. maybe we need a "refresh" button 🤔
another tradeoff could be we could periodically trigger a resort..? like maybe at boot, once countervalues are loaded, we trigger a sort? the big problem to me is that, this order being unstable, it's unclear when to update this.. are we ok having the UI updating the orders of account, which can create weird "click jacking" user experience.

**Comment by gre** [comment]
these 2 events would make sense yeah. I think basically "on app open" + "on add account" would definitely make sense to trigger a resort.
