### ISSUE TITLE
Turn accounts in sidebar into collapsable menus

### ISSUE THREAD

**Issue by durbanpoison** [LedgerHQ/ledger-live-desktop#1202]
- [x] I have checked this feature was not yet requested.

I have a lot of accounts and would like to be able to de-clutter the sidebar by collapsing them down. What I would like to see is each asset become a collapsable menu that I can click on to reveal all of the accounts for each asset. It would look something like this:

```
Bitcoin >
Ethereum v
 - Account 1  
 - Account 2  
 - Account 3  
Monero >
Zcash >
```

Also the list of assets should be in alphabetical order, right now it isn't.

#### Part of the application

Accounts

**Comment by gre** [comment]
Hi @durbanpoison, thanks for taking the time writing this :)

> I have a lot of accounts and would like to be able to de-clutter the sidebar by collapsing them down. What I would like to see is each asset become a collapsable menu that I can click on to reveal all of the accounts for each asset. It would look something like this:

I agree with the problem, but i'm not sure about the suggested solution: when we will introduce ERC20, this would not address the problem that you will have tons of ERC20, and we might introduce such nested menu for them actually (nothing was decided or even discussed yet on our side, really early stage).

We might also have a "Accounts" list screen in the future / have better way to search one.

> Also the list of assets should be in alphabetical order, right now it isn't.

it use the ordering preference that was set in Portfolio but actually we have fixed a but that was not making it refresh. #1153 


I'll close this issue in favor of #986 because i think it's the same concern that was raised in this issue.
