### ISSUE TITLE
Adding Manual Accounts + Monero

### ISSUE THREAD

**Issue by Dviros** [LedgerHQ/ledger-live-desktop#1246]
Hi,
I would like to have the ability to add manual types of accounts (such as altcoins) that are not necessarily supported by the ledger, as only to be able to "view" them as a portfolio.
Also, Monero would be awesome to add as well.

Thanks!
Dvir

**Comment by gre** [comment]
> I would like to have the ability to add manual types of accounts (such as altcoins) that are not necessarily supported by the ledger, as only to be able to "view" them as a portfolio.

what would than mean to you? what is the usecase? is it to calculate them in the portfolio globally? 

Such feature is quite complex to add as all today's account are coming from your ledger / is unified experience with the ledger device.

Today, it's out of scope of the app to allow you to track your "overall portfolio". There are apps like "Delta" that support this and manage all connections with wallets / exchanges / ..

> Also, Monero would be awesome to add as well.

can't give an ETA yet for this. It's a tricky subject (because the complexity of the architecture, with the private view key / private key).


I'll close the issue for now, because it's not in today's roadmap, but we'll open new issues when this happen.
Thanks
