### ISSUE TITLE
Quality of Life enhancements 

### ISSUE THREAD

**Issue by StaffanoS** [LedgerHQ/ledger-live-desktop#1265]
Charts don't really show changes well, unless they're quite big.
Seeing the "Week" chart is almost always a straight line.
The chart shouldn't at 0 and end at max value, it should start at the lowest value of the time and end at the max value reached during this period.
Furthermore I might suggest adding a "Day" chart, and possibly the option to give the App a name so it would resemble the early Screenshots of the app. 
There it was "Good morning, John Doe", it would make the App more personal.

**Comment by gre** [comment]
lot of feedbacks in one issue (in future please try to split them in multiple issues)

> Charts don't really show changes well, unless they're quite big.
> The chart shouldn't at 0 and end at max value, it should start at the lowest value of the time and end at the max value reached during this period.

i'm not that sure about this choice. I feel zero based graph reflect more the reality. (Not sure we really want to emphasis on the volatility of the market 😅)

> Seeing the "Week" chart is almost always a straight line.

that's true. I guess one way to solve this would be to increase the granularity (if you see in Week, we could have a 1H granularity 🤔 ).

we'll have to test this.

> Furthermore I might suggest adding a "Day" chart

not sure what the granularity would be. I don't think we can easily do that for now. because our countervalues api granularity is the Day (we don't go below 1D in term of rates precision) so it would just mean seeing your operations flow (so straight line if nothing was moved in the last 24h)

**Comment by gre** [comment]
- chart are no longer zero based
- 1h granularity will be tried soon
- day chart as well
