### ISSUE TITLE
Additional listing of fiat currencies in Countervalue

### ISSUE THREAD

**Issue by StayCoolDK** [LedgerHQ/ledger-live-desktop#1331]
Can you please also add some additional fiat currencies? I think it's very limited currently, and my native valuta (Danish Kroner) is not available. The more options, the better in my opinion, and this shouldn't be very complicated to implement.

**Comment by gre** [comment]
unfortunately we can't until our countervalues provider provide more pairs, and I don't think Danish Kroner was in the available ones, but we can double-check again

**Comment by StayCoolDK** [comment]
Isn't it possible to have multiple providers? Please do :-)

**Comment by gre** [comment]
just to be clear, it's actually backed by https://github.com/LedgerHQ/ledger-api-countervalue so it's not really up to Ledger Live. And it's also not as simple as dev work, it's also business decision.

**Comment by gre** [comment]
@StayCoolDK is there an actual exchange supporting BTCDKK ? because i can't find any, the only one I see on tradingview is.... MtGox

<img width="706" alt="capture d ecran 2018-07-31 a 09 59 29" src="https://user-images.githubusercontent.com/211411/43446195-82181fb0-94a8-11e8-80c9-9bb74de50ace.png">

with our provider, i can see we could have data from two:

```
> t.filter(a => a&&a.to==="DKK")
[ { id: 'MTGOX_BTC_DKK', exchange: 'MTGOX', from: 'BTC', to: 'DKK' },
  { id: '1BTCXE_BTC_DKK',
    exchange: '1BTCXE',
    from: 'BTC',
    to: 'DKK' } ]
```

but both no longer have data (obviously^^).

So, until we don't support inter-fiats conversions, we won't be able to offer DKK. The current approach Ledger Live is taking is to not provide **average calculated** rates (we've seen how bad this approach was in Korea in recent news for instance), but always let the user decide on the exchange. today approach is still to do one intermediary conversion (via BTC). so for instance: DOGE->BTC->EUR to calculate the DOGE->EUR (that does not exist as direct pair).

**Comment by StayCoolDK** [comment]
Hey gre i realised that blockchain.info uses Coinify as a payment merchant for credit cards also accepting DKK and the BTC/DKK pair is available to retreive on the following api: https://blockchain.info/ticker
Would be awesome to see this implemented soon, so i don't have to view my balance in USD/EUR which i never use on a daily basis.

**Comment by StayCoolDK** [comment]
Also here is a direct API from Coinify including DKK: https://api.coinify.com/v3/rates

**Comment by StayCoolDK** [comment]
@gre i'm revisiting this issue, due to the fact that you have now added more countervalue pairs, including DKK, to Ledger Live, which is awesome! However unfortunately it zeroes out all balances / is not working at all alongside many of the added countervalues. It seems like there is not a provider for the DKK currency pair and for many others. I'm just wondering why you've added it as a option in the software if you still haven't found a DKK/BTC exchange? Or are you possibly implementing something soon TM?
