### ISSUE TITLE
Implement a force restart when an important release is delivered

### ISSUE THREAD

**Issue by fdv** [LedgerHQ/ledger-live-desktop#1407]
We need to implement a "force restart" in the upgrade process

Since we're delivering the binaries with a yaml file, this one should have a "comment" section, empty or with a certain string. That yaml file needs to be checked by the live / returned by the download server and if the string is present, force an upgrade / restart within 5 seconds with a nice modal explaining what's going on.

Also we need to check if a new release exists every 30 minutes and not only when launching the application.

This will force the users to upgrade when we have an important release

**Comment by fdv** [comment]
@dasilvarosa we'll need some wording here please, like "We've released an important update, the app will upgrade itself and restart in 5... 4... 3... 2... 1..."

**Comment by gre** [comment]
make sure to discuss with security team before implementing. as it was said in https://github.com/LedgerHQ/ledger-live-desktop/issues/1243 I don't think we ever should remotely force an update because can be a potential backdoor. IMO users should always be free to use whatever version of the app, I feel we just need to have a big banner in case it's outdated and for critical update a big disclaimer so I think https://github.com/LedgerHQ/ledger-live-desktop/issues/1243 is the way to go.

**Comment by gre** [comment]
the key point to me is that an app update should be user's action. I would stick to normal way all apps are doing it, by asking the user at boot of the app. maybe showing what the update is about so if it's critical, it will be obvious for users.
