### ISSUE TITLE
No window size & position save after app restart

### ISSUE THREAD

**Issue by andreasmaks** [LedgerHQ/ledger-live-desktop#1428]
#### Ledger Live Version and Operating System

- tested on Ledger Live v1.1.6
- Platform and version: Mac 10.13.6

#### Expected behavior

- resize and repositioning window
- reopen App 
- app opens in **new** size and position

#### Actual behavior

- resize and repositioning window
- reopen App 
- app opens in **default** size and position

**Comment by andreasmaks** [comment]
Any updates on this?

**Comment by gre** [comment]
the issue is that

https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/src/main/app.js#L72

and

https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/src/main/app.js#L80

seems to be saved like in a different db location

https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/src/main/app.js#L98-L99


it's an easy fix if anyone want to tackle it down.

**Comment by juan-cortes** [comment]
Added a pr for this since it was already obvious how to fix it :trollface:

**Comment by juan-cortes** [comment]
This is done :)

**Comment by clintnetwork** [comment]
Not really done,

When you maximize app, you close and you reopen the maximized state is not saved.

![image](https://user-images.githubusercontent.com/5221349/63531490-e9892400-c508-11e9-9088-9a928b888229.png)

**Comment by juan-cortes** [comment]
It's working on mac, damn..
