### ISSUE TITLE
Using smartbit instead of blockchain.info

### ISSUE THREAD

**Issue by NicolasDorier** [LedgerHQ/ledger-live-desktop#1430]
When clicking on the `View in Explorer` button on a transaction, we are redirected to blockchain.info.

![image](https://user-images.githubusercontent.com/3020646/44273901-ae13a400-a27b-11e8-98ea-8da0c2c08cdb.png)

Would it be possible to use smartbit instead?

I think it would be healthy to decrease reliance on them for privacy reason.

Blockchain.info is used for a huge number of wallet and lot's of people access their API and block explorer, this is very interesting information for chain analysis companies. And I do not trust them to not make profit out of it.

**Comment by juan-cortes** [comment]
Problem for this one is it gets the explorer url from [a separate repo ](https://github.com/LedgerHQ/ledger-live-common/blob/master/src/explorers.js) and although refactoring it to be an array instead of a single url would be easy enough, this is not the only app relying on it. Overriding the explorer locally on your app might be easier..

**Comment by NicolasDorier** [comment]
Overriding the setting for myself do not solve the privacy issue.
The problem is that everyone are leaking their transaction to `blockchain.info`, not just me.

**Comment by gre** [comment]
@juan-cortes yeah we can probably consider switching to an array with many choices and introducing a new settings to select it.

**Comment by gre** [comment]
will close in favor of https://github.com/LedgerHQ/ledger-live-desktop/issues/1359
