### ISSUE TITLE
Opt-in to get derivations for accounts on import?

### ISSUE THREAD

**Issue by juan-cortes** [LedgerHQ/ledger-live-desktop#1435]
**Update**
I can just follow what Ripple is doing and break on the first empty derivation, but this means someone with an account on a custom derivation path wouldn't be able to get to it.

------------

Seems a bit overkill to rely on the user stopping the derivation loop (0-255) since each turn of the loop will most likely trigger an API call. I'm sure the number of calls to Horizon, in this case, is a trifle and we could ignore it, but perhaps simply pulling the main derivation and offering the user to opt-in into getting a specific/range of derivations?

I just hate seeing this. Also, it makes the import needlessly long since most people (some people?) won't realize "_stop_" means "_We've already got all we need from the ones listed, we are looking for more, if all your accounts are listed you can stop_"

![image](https://user-images.githubusercontent.com/4631227/44403400-9f1b4300-a554-11e8-97b9-35105665a01e.png)

Maybe simply changint _stop_ to _done_ would be clearer? Granted my rural internet is not the best at the moment but 255 calls at 600B, syncronously, means over a megabyte and 1.5 minutes in my case.
![image](https://user-images.githubusercontent.com/4631227/44403642-4b5d2980-a555-11e8-9bb1-4fde6ed9826b.png)

**Comment by gre** [comment]
normally we should stop at the first empty account, per https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki spec:

> Accounts are numbered from index 0 in sequentially increasing manner. This number is used as child index in BIP32 derivation.

and

> Software should prevent a creation of an account if a previous account does not have a transaction history (meaning none of its addresses have been used before).

> Software needs to discover all used accounts after importing the seed from an external source. Such an algorithm is described in "Account discovery" chapter.



+ see also section about Account discovery : https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#account-discovery and also: "Address gap limit is currently set to 20. If the software hits 20 unused addresses in a row, it expects there are no used addresses beyond this point and stops searching the address chain.". We sometimes have to increase this 20 to like 100, because some wallets on some blockchains didn't respected that (I can't remember which coin had the case, @KhalilBellakrid knows)


is there anything I missed to understand in your usecase?

**Comment by juan-cortes** [comment]
Totally my fault on this one, **I didn't read the wiki on that.** Sorry. I see that for example, the Ethereum bridge relies on `mandatoryEmptyAccountSkip` which can be either 10 or 30, which sort of agrees with the wiki you mention. Yet Ripple stops at the first one. Would it be safe to use the _20 unused addresses in a row_ then?

Meaning if path 44'/148'/0' through 44'/148'/2' have accounts I'd stop at 44'/148'/32'?
Thanks for linking me to all these resources @gre

**Comment by gre** [comment]
yeah Ethereum is definitely a special case, the problem is that MEW didn't respect this specification and have allowed users to chose arbitrary derivations when selecting an address, forcing us to introduce this "mandatoryEmptyAccountSkip" mechanism. We've chosen to use "10" for both the MEW derivation path of ETH and ETC, but not on the new derivation that follows BIP32 spec.

e.g; for eth, we'll always try these paths:

```
44'/60'/0'/0
...
44'/60'/0'/10
```

whatever if there are accounts, and then we'll try once 

```
44'/60'/0'/0/0
```

and if there is none, it stops.



> Would it be safe to use the 20 unused addresses in a row then for the Stellar bridge I'm writing?

mmh, why? normally you should stop at the first **for account iterations**. The Address gap limit mentionned in the spec is only for discovering addresses within a given account.

so for instance, you are on account 44'/148'/0' , when you iterate on address_index in `44'/148'/0' / change / address_index` you can iterate on 20 unused until stopping it. ( cc @KhalilBellakrid if you can confirm this is your current libcore impl )

**Comment by juan-cortes** [comment]
Oh I see!, that makes sense.

Might as well ask here about the fact that Stellar doesn't follow the standard for path derivation and needs to follow https://github.com/stellar/stellar-protocol/issues/61#issuecomment-342478953 the `m/44'/148'/x'` derivation pattern. Then according to [hw-app-str/src/utils.js](https://github.com/LedgerHQ/ledgerjs/blob/6a922867fe600b85e0bb2a3feab28914a89a0b6d/packages/hw-app-str/src/utils.js) it needs to use an all-hardened path. 

So I'm currently rewriting the path as I receive it in the `getAddressForCurrency`  stellar implementation. This doesn't seem good though but unless I do this when going through `EnsureDeviceApp` which explicitly calls the `standardDerivation` would send `${purpose}'/${coinType}'/${x}'/0/0` to `getAddress`.

My question being, is overriding the path inside the implementation of the stellar getAddress fine, or should the EnsureDeviceApp `getAddressFromAccountOrCurrency` stop relying directly on the standard, or... something else.
