### ISSUE TITLE
ONTOLOGY 

### ISSUE THREAD

**Issue by KMFDM29** [LedgerHQ/ledger-live-desktop#1455]
As I can use other coin if their there is no in this list but there is in MANAGER? For example  ONTOLOGY?
![26-08-2018 031205](https://user-images.githubusercontent.com/41021204/44621268-7ee9dc00-a8e6-11e8-83e2-6ce3794c13de.jpg)

**Comment by juan-cortes** [comment]
That means that the app doesn't currently have an integration for the coin, it's up to the community to develop it in most cases since integrating hundreds of coins is unfeasible by the ledger team, but someone might correct me if I'm wrong. 

In your particular case, you could use the official wallet meanwhile https://github.com/ontio/documentation/blob/master/walletDevDocs/How%20to%20install%20and%20use%20ONT.md or get that integration going if you have the know-how

**Comment by KMFDM29** [comment]
Thank you!  Is it safe to use this app?

**Comment by juan-cortes** [comment]
Seems legit, but I know nothing about the coin nor the developers involved. What I mean is it seems to come from the makers of the coin itself, so it's as safe as it gets, you still need to manually confirm the transactions with your device, they can't just skip that

**Comment by KMFDM29** [comment]
Thank you!

**Comment by MortalKastor** [comment]
#1427 #1130
