### ISSUE TITLE
HELLO! Why is this happening?

### ISSUE THREAD

**Issue by KMFDM29** [LedgerHQ/ledger-live-desktop#1465]
#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**

#### Steps to reproduce the behavior

![28-08-2018 053006](https://user-images.githubusercontent.com/41021204/44681466-002aa580-aa84-11e8-85e8-a56ca79295ef.jpg)

**Comment by KMFDM29** [comment]
Half of the applications are not installed at all. Dogecoin Bitcoin Gold  Dash Litecoin  Tron...

**Comment by meriadec** [comment]
Not sure I understand the problem here :thinking: 
What I can see in screenshot is that you are trying to install an app that require the latest version of Bitcoin or Ethereum to be installed on your device.

The red arrow is pointing on an account, so not sure what to understand here.

Feel free to reopen if the problem persists with latest BTC/ETH apps installed and make sure you provide all useful informations (Ledger Live version, apps versions, etc.)

**Comment by KMFDM29** [comment]
The red arrow means that the Bitcoin application is installed .

**Comment by meriadec** [comment]
No, it means that you have imported a BTC account.

- What is the application you are trying to install?
- What is your installed BTC app version (you can see it on your device by navigating in the app menu)?
- What is the BTC version that is showing when you search "Bitcoin" in the Ledger Live manager page?

**Comment by KMFDM29** [comment]
This version of the app INSTALLED
![28-08-2018 180934](https://user-images.githubusercontent.com/41021204/44709810-e160f900-aaed-11e8-81f3-1339cccc33f8.jpg)

**Comment by KMFDM29** [comment]
It was possible to establish only when deleted all applications and Bitcoin.Then I installed bitcoin and everything else.The problem apparently was in this.
