### ISSUE TITLE
Can't remove Ethereum Classic or Ethereum

### ISSUE THREAD

**Issue by gmourani** [LedgerHQ/ledger-live-desktop#1533]
Hello,

Ledger Live with Ledger Nano S version 1.4.2 on macOS High Sierra 10.13.6.
I've reinstalled my macOS from scratch, then Ledger Live, then removed all App from catalog, but Ethereum Classic and Ethereum cannot be deleted ! Try everything, rebooted, close, open Ledger Live, same result.

Even if Ethereum Classic has been uninstalled, it's still there !
For Ethereum, the message is different, Sorry this app is required !

Again, nothing else is presently installed on the Nano S stick.

Regards,
![screen shot 2018-09-23 at 8 41 43 pm](https://user-images.githubusercontent.com/20328799/45935326-5e11b680-bf78-11e8-8ccc-ded31867fd70.png)
![screen shot 2018-09-23 at 8 41 57 pm](https://user-images.githubusercontent.com/20328799/45935327-5e11b680-bf78-11e8-81b3-5d80a04bc99b.png)

**Comment by juan-cortes** [comment]
The _"Sorry this app is required"_ is because Ethereum classic depends on Ethereum to work, it corresponds to the error `ManagerUninstallBTCDep` which has the description 
>Uninstall the Bitcoin or Ethereum app last.

This means that you need to remove Ethereum classic before you can uninstall Ethereum, I'm sure you understand this. I have the same local setup as you so I tried installing Ethereum classic and then uninstalling it, sadly this worked fine and the app was removed.

If you still have your seed (you do, right?) you could try setting up the device again from the seed (**I take no responsibility if you have the seed wrong**) which would result in a device with zero apps.

Settings->Device->Reset all if you want to follow that route.

**Comment by meriadec** [comment]
In order to ease to reproduce on our side (just tested and uninstall was successful), is it possible for you to clone and console.log the `applicationList` variable? 

https://github.com/LedgerHQ/ledger-live-desktop/blob/3be9d3fee641224eae9cadeff861367f19226dac/src/components/ManagerPage/AppsList.js#L122

for setup instructions: https://github.com/LedgerHQ/ledger-live-desktop#setup

**Comment by gmourani** [comment]
What do you mean by clone and console.log the applicationList variable?
Do you want me to clone the code, then remove the line at position 122, then rebuild ?
