### ISSUE TITLE
"ETC" app cannot be uninstalled since it is no longer listed in the Manager

### ISSUE THREAD

**Issue by davidbindel** [LedgerHQ/ledger-live-desktop#1542]
#### Ledger Live Version and Operating System

ETC app 1.1.3

- tested on Ledger Live 1.1.11
- Platform and version: Windows 10

( I suspect this *might* a better description of issue #1533 )

#### Expected behavior

I should be able to uninstall the Ledger app named "ETC", but cannot since the Manager has delisted it and added a distinct app named "Ethereum Classic".

#### Actual behavior

I have no means of uninstalling the app named "ETC". (For comparison, I can install and uninstall the "Ethereum Classic" app.)

A side effect of this is that I am unable to uninstall or upgrade the Ethereum app since the "ETC" app depends on it.

#### Steps to reproduce the behavior

1. Open Ledger Live and connect Ledger.
2. Navigate to the Manager in Ledger Live.
3. Look for an app named "ETC", hoping to uninstall it.
4. No app named "ETC" can be found in the Manager.

**Comment by meriadec** [comment]
https://github.com/LedgerHQ/ledger-live-desktop/issues/1533 is probably related
@amougel what do you think?

**Comment by omarabid** [comment]
@gre This is not solved. I can't uninstall "Recovery Check", "Passowrds" and "SSH/PGP Agent". I haven't used my Ledger for over a year and now I connected it and it seems nothing works. That's really bad for something which is supposed to provide stability. (PS: I'm trying to uninstall apps so that I can upgrade from 1.4.2 to the latest firmware version)

**Comment by gre** [comment]
@omarabid you need to enable Developer mode to see them https://support.ledger.com/hc/en-us/articles/115005200649-OpenPGP
