### ISSUE TITLE
Manager page: "Some connection failed, so please try again."

### ISSUE THREAD

**Issue by douglasdeodato** [LedgerHQ/ledger-live-desktop#1655]
Version
Ledger Live 1.2.5
windows 10

I tried open the manager today to add a new wallet and I keep getting this error bellow, any ideas? what it is going on? I have checked : http://status.ledger.fr/  

I usually get a message in my ledger to allow this action, this message did not appear

anyway could be good show to the user what error exaclty it is going on ?

![led](https://user-images.githubusercontent.com/993318/48842174-b4358700-ed7a-11e8-9f43-743e2dcf6dbc.jpg)

**Comment by meriadec** [comment]
Given your screenshot the device is successfully detected & so is the fact that you are on the dashboard screen on the device.

The third step (genuine check) is failing, that could be caused by multiple things:
- cable issue / usb issue. Does it do the same thing while using another computer / cable ?
- network issue. Do you have particular setup, like corporate proxy? This could infer on the genuine check behaviour (relatable: [#1035](https://github.com/LedgerHQ/ledger-live-desktop/issues/1035), [#1073](https://github.com/LedgerHQ/ledger-live-desktop/issues/1073)). Can you try with different network?

If this doesn't help, I would advise to contact support (https://support.ledgerwallet.com/) and provide your logs (`Ctrl`+`e`).
