### ISSUE TITLE
Offline account and app management

### ISSUE THREAD

**Issue by okipol88** [LedgerHQ/ledger-live-desktop#1713]
#### Ledger Live Version

- Ledger Live 1.2.6

#### Part of the application to improve

Creating accounts would be better done offline. The installed apps should also be available as a standalone package with a fatter installer. Currently the procedure from initialization to using the ledger requires internet connectivity for the setup. Or am I missing something?

**Comment by gre** [comment]
The only problem I see is that you can't do it offline, not in the current paradigm we have taken which is to use BIP44 spec and to offer the simplest experience for the user (not having to chose from a list of derivation like MEW is doing).

BIP44 tells us that you must guarantee that you can't create an account N+1 if account N is empty (you don't leave holes, that allows to not have to scan infinitely to know where are your funds)

More generally Ledger Live idea is to be "Live" and is not really designed for offline, you might need another solution for different usage.

The second discussion @danuker raised is different, it's on the genuinecheck/manager/apps feature, it's an interesting discussion that need to continue on our Slack Devs if possible because i think it's beyond Ledger Live.

**Comment by okipol88** [comment]
@gre So why not create an N = 0 account offline only. For those who seek more acounts then give the possibility to create more (N + 1) accounts. This also conforms as no hole will be possible.

**Comment by gre** [comment]
You can't really create an account offline: you will not know how much it have, we will not know what is the latest address that didn't receive funds yet to preserve a bit bitcoin's privacy and to not re-use addresses ( https://en.bitcoin.it/wiki/Address_reuse ). When you do `Receive` for bitcoin and alts, we will only propose such new address (internally we call them "freshAddress")
