### ISSUE TITLE
Raspberry Pi Support

### ISSUE THREAD

**Issue by Kris191** [LedgerHQ/ledger-live-desktop#1728]
- [ ] I have checked this feature was not yet requested.

Support for installation on a Raspberry Pi OS using arm architecture. It has been discussed previously but no updates.

Presently you cannot execute the AppImage file in a Pi OS even when you have a 64 bit version installed.

Thanks

Kris

**Comment by meriadec** [comment]
No update because no advancement nor ETA for ARM support.

It's not a priority, because few people ask for it compared to the amount of work it involves. AFAIK [lib-ledger-core](https://github.com/LedgerHQ/lib-ledger-core) doesn't have ARM target and it's one of our critical deps, among other native deps that would require to be compiled for ARM, e.g node-hid. it would also require additional electron-builder target, which means additional QA testing, etc.

IMO a ledger-live web interface would be the de-facto solution for maximizing compatibility.

closing in favor of #1131.
