### ISSUE TITLE
Synchronization error

### ISSUE THREAD

**Issue by clintnetwork** [LedgerHQ/ledger-live-desktop#1733]
When i launch my Ledger Live Wallet, i've this error, when i click refresh it does not work, what is the problem ?

Thank you

![image](https://user-images.githubusercontent.com/5221349/50726474-d4908980-110d-11e9-92e9-7ed9b6b31c32.png)

**Comment by Transisto** [comment]
Could be that your did too many transaction and have too many addresses.

Ledger syncing is shit  https://github.com/LedgerHQ/ledger-live-desktop/issues/1721

**Comment by Luuk2016** [comment]
Are you receiving a lot of mining proceeds?
If yes, read this post: 
https://support.ledger.com/hc/en-us/articles/115005165209-Receive-mining-proceeds

**Comment by clintnetwork** [comment]
Hi sorry,

I've removed the appdata/ledger folder and it's works for now

**Comment by gre** [comment]
you can do a clear cache when this happens.
It might be a glitch in our explorers or in internal libcore.
nothing we can fix in Ledger Live itself.

**Comment by clintnetwork** [comment]
Sure but if people need to remove their appdata folder it's not very convenient ^^

**Comment by gre** [comment]
you should not have to remove appdata folder. You only need to go to Settings and do Clear Cache.

**Comment by peddlero** [comment]
I also did the ledger live updates and did the clear cashe - it does not work. Any more ideas?

**Comment by Jariben** [comment]
Hi. I have the same problem! I have cleared caché several times and Live is updated. What can I do? Thanks. It still does not synchronice

**Comment by peddlero** [comment]
In my case the Live update helped. But after doing the update it did not work. I did not know why and then I noticed I have two Ledger Live icons on my computer display. Second one appeared after the update. One did not work and the other worked :)

**Comment by conyisland** [comment]
I have the same Problem, Ledger Live does not synchronize since 5 Days i opend the Wallet the first Time since Month. I updated to Version 1.6.0 then it worked for a few Minutes until it did turn red again, then i updated to 1.20.0, cleared my Cache several Times, restarted my Computer (MacBookpro) 10 Times, and wrote 2 Mails to Ledger Support with no answer so far and it still does not work. That App for Desktop has that Problem since a long Time and it ocures again and again.

I wanted to activate my Account at BTCPayServer.org, normaly the Website does recognize a Ledger Wallet to generate the xpub-Key and API-Keys automaticly, but this does not work either with no Browser, probably because of the App is not synchronizing?

This way they will never bring more normal users into Cryptos, it is much to awkward to deal with all this problems, with Transfer, Apps, Supports, Programs, 10 Accounts etc.

**Comment by clintnetwork** [comment]
Personally I stopped to use Ledger, so many problems when you keep it in an armory and you use after some months, I had about 5K STRAT and unable to synchronize on desktop and mobile, so I was blocked to spend money!

Ledger is quite cool, but this problem is not allowed for a device at 120+ EUR.

**Comment by conyisland** [comment]
Now i solved all Problems and i thougt i pass it on, also for other Users that look for Solutions in Future.

The "synchonization error" i did only get rid of by resetting Ledger Live: **Settings/Help/Reset Ledger Live.** Make sure you have your assets and Apps all saved on Hardware Device. Then you just have to "Restore" your Live App (not a complete new set up) by following the Instructions and set up your Accounts again, after that sychronizing worked again.

According the BTCpayserver: to transfer your xpub-key to your btcpayserver-storeaccount (Derivates Scheme) you have to click on "Vault" instead of Ledger Wallet, and download a little Program from github. With that Program it worked to transfer the xpub-Key and BTC-Addresses to BTCPay/your store Account.
