### ISSUE TITLE
ledger-live-desktop wont launch - symbol lookup error

### ISSUE THREAD

**Issue by Cerv4ntez** [LedgerHQ/ledger-live-desktop#1863]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.6.0 and all prior versions.
- Platform and version: Ubuntu 18.10

#### Expected behavior

simply launch

#### Actual behavior

when i try to launch it i get the following:
./ledger-live-desktop-1.6.0-linux-x86_64.AppImage 
/tmp/.mount_ledgergc5JeU/app/ledger-live-desktop: symbol lookup error: /tmp/.mount_ledgergc5JeU/app/ledger-live-desktop: undefined symbol: _ZN12v8_inspector8protocol8Debugger3API6Paused10ReasonEnum3XHRE

#### Steps to reproduce the behavior

this has been happening from the first version of ledger live availlable for me. i searched wide and far for a solution or even someone else with the same problem but to no avail.
from what i saw it might be connected to electron, but i dont understand the connection.
please help.

**Comment by Xa52c** [comment]
same, did you find a solution to this?

**Comment by zeroping** [comment]
Same issue on Debian 10. Tested 1.15.0 through 1.20.0. Same error. Can't use this at all at the moment.

Demangled, this symbol is "v8_inspector::protocol::Debugger::API::Paused::ReasonEnum::XHR". Still have no idea what that means though.

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

Unfortunately we did not reproduce on our side, it might be related to some dependencies, but on our side we are able to run Ledger Live desktop on Linux.

If you have ideas on the root cause of this it would be good to know but it's likely a problem more on Electron side than on our side.

We recently have upgraded to Electron 9 (please check if the bug is still happening) and will continue upgrading to newer version of Electron which hopefully will be better and better.

**Comment by zeroping** [comment]
Agreed. Things seem to work now on version 2.11.1 on the same Debian 10 machine. No idea what it was, but yes, it is fixed for me.

**Comment by gre** [comment]
very likely related to Electron version
