### ISSUE TITLE
Add Ethereum's ERC20 tokens support

### ISSUE THREAD

**Issue by luzzif** [LedgerHQ/ledger-live-desktop#1909]
I would love Ledger Live to support Ethereum's ERC20 tokens. Both to see transaction and to see their correct portfolio value.

I would also **really love** to help implementing the feature, if any help is needed. Is there some public conversation on the subject somewhere?

**Comment by guerrap** [comment]
I'd like to help, too.

**Comment by gre** [comment]
Thanks for the issue and for proposing your help.
I feel this topic is not so easy for community to take because there are many dependencies attached to it (if it was just on Live, we would have finished it way earlier). One of the dependency is to have our backend exposing all the data we need. The good news is this is happening! We've been checkmark-ing a long list in the past months to allow implementation of ERC20. We have some work ready, some continuing (for instance here https://github.com/LedgerHQ/ledger-live-common/pull/189 ), and some design getting done on the subject.

We are aware this is a long waited feature and very important topic, this is why we are going to address it soon as part as other features.

For tasks that OSS community can take we have started using the label "good first issue". We probably should try to write more of these in the future.

**Comment by luzzif** [comment]
Well thanks for the quick response.

It's awesome seeing you guys are working on the topic. 
The Ledger Live experience is just really smooth but I feel like adding this feature would certainly help spreading adoption even more.

Thanks for the hard work!
