### ISSUE TITLE
Balance in "Account" is not correct (output/unspent)

### ISSUE THREAD

**Issue by carldex** [LedgerHQ/ledger-live-desktop#2190]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.11.0**
- Platform and version: **Win10 x64**

The balance shown in "Account" of the LTC shows a value different from that shown in "Operation details"

In "Account" when I click on LTC shows, I think,  the transaction before sending the change to the change address (without fee) and in "Operation details" show the correct real value after sending change.

I noticed that in "Send" the value shown is also incorrect
I have not tested beyond the LTC
![LTC1](https://user-images.githubusercontent.com/52790805/61236334-242fbd80-a70e-11e9-8d99-75c5a6f4fac5.jpg)
![LTC2](https://user-images.githubusercontent.com/52790805/61236348-28f47180-a70e-11e9-9bcb-4a078d0a38e3.jpg)
![LTC3](https://user-images.githubusercontent.com/52790805/61236359-2db92580-a70e-11e9-8183-47ca9b8f30fe.jpg)

**Comment by gre** [comment]
It looks like your account was not fully emptied before, that's why.

<img width="148" alt="Capture d’écran 2019-07-15 à 19 53 59" src="https://user-images.githubusercontent.com/211411/61237228-4e977000-a73a-11e9-8600-4430a1db736c.png">

```
0.09887+0.3926-0.4903 ~= 0.00117
```

which was your balance before you do the 35 LTC transaction. (I say `~=` here because the operation value displayed in the list are rounded, precision is given in the operation detail of each)

so 25.00687 +  0.00117 is about 25.008 which is your balance (modulo the approximation of what i explained in previous sentence)

**Comment by carldex** [comment]
What I mean is: why the final balance in the "Account" does not appear the "unspent" of the blockchain, 35.00687 LTC?

Appears 35.007986 LTC (or 35.008 rounded in Blockchain).

**Comment by gre** [comment]
because account funds are on multiple addresses. address don't get reused for better privacy.

https://en.bitcoin.it/wiki/Address_reuse

**Comment by carldex** [comment]
The Reuse address I understood ...

What I did not understand is why the blockchain balance is not equal to the balance of the "Account"

It's not a question of rounding, check well the screenshoot ...

![LTC4](https://user-images.githubusercontent.com/52790805/61240657-20a13400-a718-11e9-9040-296eccc95ab2.jpg)

**Comment by gre** [comment]
because `34kWYv...` address is not the only place you have your balance, you probably have another address (or 2) that still have the other 0.00117

**Comment by carldex** [comment]
I think I'm finally understanding ...

And is there any way to know the balances in the addresses used by Nano?

(And thanks for your patience)

**Comment by gre** [comment]
Not yet but that definitely would be a good feature to add.
