### ISSUE TITLE
Tezos Ledger live IOS app support for custom derivation path.

### ISSUE THREAD

**Issue by logart89** [LedgerHQ/ledger-live-desktop#2559]
I have checked this feature was not yet requested.

 I can't access my funds because they are in a different derivation path, your default derivation path is the Tezbox derivation path, the derivation path that i use is just 1 number different from tezbox, please add a way for custom derivation path!

**Comment by upandbeyond** [comment]
Can you update Tezos support in Ledger Live to import additional Galleon accounts besides the default account? I created 44'/1729'/0'/0'/1' & 44'/1729'/0'/0'/2'.. Right now you only import 44'/1729'/0'/0'/0'. Can you just update Ledger Live (PC version) so that it offers to import these other addresses if they are being used? You don't need to modify the GUI for that. Thanks.

**Comment by logart89** [comment]
> 
I was recently suggested to support 44'/1729'/0'/<account>' because some users iterated on the 4rd field instead, is this something that would works for you? (in other word, are you on 44'/1729'/0'/1' ?)

Yes, that would work for me! Please add 44'/1729'/0'/1 at least.

Yes because you have 44'/1729'/0'/0 and 44'/1729'/1'/0 but not 44'/1729'/0'/1? 

44'/1729'/0'/1 is on the the 3 option that are commonly used.

**Comment by logart89** [comment]
I hope my message above is seen!

**Comment by gre** [comment]
Yes :) that path should be supported. It will be included in our next release (ETA 1 month).

**Comment by upandbeyond** [comment]
@gre Will you also support 44'/1729'/0'/0'/1'? Thanks.

**Comment by gre** [comment]
@upandbeyond yes

**Comment by logart89** [comment]
@gre The ledger live app has an error, it won't add any tezos account. Infinite synchronizing thing.
