### ISSUE TITLE
Nano S not recognized by ledger manager

### ISSUE THREAD

**Issue by Zizaerion** [LedgerHQ/ledger-live-desktop#2595]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.20.0**
- Platform and version: **Linux mint 19.3 latest updates as of 02/15/2020 and udev rules**

#### Expected behavior
manager recognizes and authenticates the nano S

#### Steps to reproduce the behavior
Plug in the nano S, attempt to connect to the ledger manager. It'll fail to detect that the nano S is on the dashboard and will not allow authentication.  The experimental usb settings also don't help.

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue is often due to udev rules but can happen for various reasons.

For that reason we prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )

**Comment by Zizaerion** [comment]
Sure, I'll get those sent off so we can get this resolved.  I usually use the Nano X now, but it was just something I noticed when connecting my Nano S backup to it just to see.

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release https://github.com/LedgerHQ/ledger-live-desktop/pull/2596
