### ISSUE TITLE
Receive address should stay visible after approving it

### ISSUE THREAD

**Issue by Zaczero** [LedgerHQ/ledger-live-desktop#2675]
I'm used to first approving the address in Ledger Live (making sure it's 'trusted') and then re-checking it after copy-pasting to external program with the 'trusted' one in Ledger Live popup. Currently after approving the address and copying it I cannot say if the address has been changed or not as it's no longer there. This isn't very convenient for me.

#### Ledger Live Version

- Ledger Live **2.0.0**

#### Part of the application to improve

* "Receive" modal window

**Comment by gre** [comment]
> I'm used to first approving the address in Ledger Live (making sure it's 'trusted') and then re-checking it after copy-pasting to external program with the 'trusted' one in Ledger Live popup. Currently after approving the address and copying it I cannot say if the address has been changed or not as it's no longer there. This isn't very convenient for me.


Unfortunately you are used to a way that is not enough secure.

We had in the past, and even recently, a few attacks that were hijacking the content of the copy-paste clipboard. Ultimately you should not trust what Ledger Live itself is showing you as address because the Copy feature might be compromised (and any software can hijack clipboard content).

What you should do it FIRST copying the address, pasting it to the place you will use it (like an exchange? or to a friend?) and only then, on that paste, SECONDLY verying the address on your device.
