### ISSUE TITLE
Problem after installing Ledger Live

### ISSUE THREAD

**Issue by rotaslan** [LedgerHQ/ledger-live-desktop#2689]
Hi,
I just installed Ledger Live on my new computer running Win 10 Pro 64 bit Os, but the program gives an error, anyone does any idea what is this or how to solve it ? Thanks.
![Screen shot](https://user-images.githubusercontent.com/61861467/76056844-a7956c00-5f88-11ea-9aa0-a2db5fee4574.PNG)

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. I'm closing because this is dup with #2680

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
