### ISSUE TITLE
[MacOS] Ledger Live 2.0.1 Can't Proceed with Transferring

### ISSUE THREAD

**Issue by jinpinggou** [LedgerHQ/ledger-live-desktop#2715]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.0.1**
- Platform and version: **Mac 10.15.3**
- Ledger Nano S firmware **1.6.0**

#### Expected behavior

When transferring Bitcoin, I successfully entered recipient, amount, and confirmed the summary. In the last step "Device", it is expected to verify and sign the transaction and asked for my final confirmation of the transaction on Nano S. 

#### Actual behavior

Instead, in the last step "Device", the final confirmation never shows up, it shows "Loading" forever, until prompts "Oops, the internet seems down" after a long wait of 10 minutes

#### Steps to reproduce the behavior

Please see the screenshots and logs attached.

<img width="496" alt="Screen Shot 2020-03-15 at 1 57 01 PM" src="https://user-images.githubusercontent.com/16055149/76696407-1cbe1b00-66c6-11ea-82b6-681da6fb1ed8.png">
<img width="377" alt="Screen Shot 2020-03-15 at 1 57 14 PM" src="https://user-images.githubusercontent.com/16055149/76696409-2fd0eb00-66c6-11ea-9399-dfbb9bd89279.png">
<img width="495" alt="Screen Shot 2020-03-15 at 2 36 04 PM" src="https://user-images.githubusercontent.com/16055149/76696819-732d5880-66ca-11ea-8ce6-4a76f46d3660.png">

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

To my knowledge, this may be due to various factors:

- depending on your bandwidth and location the Ledger Live <-> Explorer API can be slow (are you in China? unfortunately we have some bad ping time at the moment and this is a infra topic we are aiming to solve)
- depending the size of your accounts there might be a lot of Ledger Live <-> Explorer API calls getting done (so it might take time to "synchronize" the account)
- depending on your account and transaction, the number of UTXOs can be important which can take time to stream to the device.


Unless you do want to investigate on your side, we prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )

**Comment by jinpinggou** [comment]
Thank you for your timely answer. 

I've sent my problem with screenshots and log files to the customer support. I will follow up by email. 

I'm in China but I use VPN all the time. Syncing is a headache as well. For the last two days, I can't even successfully sync even with VPN. Before this period, it works fine. Today the syncing is on and off. Ledger has a large China user base. Solving the syncing problem is really in need.

If the customer support can provide helpful feedback on this issue, I will post it here to help more users.

**Comment by gre** [comment]
> Ledger has a large China user base. Solving the syncing problem is really in need.

I totally agree with you. I was in China 6 months ago and the ping with our explorers were really slow (VS from europe) even over VPN, due to the fact we don't have an infra yet available in Asia, things could be better that way.

**Comment by leoliew** [comment]
A year has passed and the situation has not improved. Are you going to abandon the Asian user group?
