### ISSUE TITLE
Ledger Live 2.0.1 doesn't start because of sandboxing issue

### ISSUE THREAD

**Issue by 1989gironimo** [LedgerHQ/ledger-live-desktop#2718]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.0.1
- Platform and version: PureOS (debian testing based) 

#### Expected behavior

It should start.

#### Actual behavior

It doesn't start and throws an error:
./ledger-live-desktop-2.0.1-linux-x86_64.AppImage 
[6082:0316/080937.973448:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/user/1000/.mount_ledgerRAecks/chrome-sandbox is owned by root and has mode 4755.

#### Steps to reproduce the behavior

Try to start the application on this system.
Disabling the sandbox with --no-sandbox is working.

**Comment by gre** [comment]
@1989gironimo are you running the app in root mode? maybe you should try to run it in a normal user mode, it seems it doesn't work in sudo mode.

**Comment by 1989gironimo** [comment]
Nope, running as a normal user...

**Comment by mcgarebear** [comment]
I am also experiencing this issue on Debian 10 after my weekly patching - but not sure if coincidental

```(09:11:39) ~/bin$ ./ledger-live-desktop-2.0.1-linux-x86_64.AppImage 
[9622:0316/211153.172914:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_ledgerDppEbB/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
```
Passing the `--no-sandbox` flag works around the issue as mentioned, no problems with sync or anything after starting as far as I can tell.

**Comment by obigroup** [comment]
Same problem with Debian 10 with version 2.0.0.

./ledger-live-desktop-2.0.0-linux-x86_64.AppImage
[6082:0316/080937.973448:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/user/1000/.mount_ledgerRAecks/chrome-sandbox is owned by root and has mode 4755.

How to solve it without using --no-sandbox ?

**Comment by dud225** [comment]
This problem stems from [Electon](https://github.com/electron/electron/issues/17972).
There are 2 workarounds on Linux:
- disable the sandbox:
```./ledger-live-desktop-2.0.1-linux-x86_64.AppImage --no-sandbox```
- enable the use of user-namespaces (disabled by some distros):
```sudo sysctl kernel.unprivileged_userns_clone=1```

**Comment by t0rv1c** [comment]
+1 here!
I am on Bionic and when I start the Ledger Live AppImage, I get "FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_ledger2m51zW/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)"
If I start the app with --no-sandbox, it's ok.
Any help would be greatly appreciated. Thanks!

**Comment by Andrewskiz** [comment]
Still having this issue on Debian 10 with Ledger Live v2.4.1

**Comment by jlopp** [comment]
This issue is pretty annoying, mainly because I open Ledger Live infrequently enough that I forget about the command line flag and have to find this issue again. Any way to fix your electron implementation to automatically skip this check?

**Comment by gre** [comment]
we will look at this again. I wonder if this is fixed in our upcoming Electron 9 migration (#2954). @valpinkman can you give a look at this when you have something stable there? thanks

**Comment by 1989gironimo** [comment]
The issue still persists.

**Comment by dud225** [comment]
Debian has finally enabled user namespaces by default starting from the kernel 5.10: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=%23898446#117
I can confirm to be able to launch the latest LL release without having to disable the Chromium sandbox.

**Comment by jlopp** [comment]
Confirmed, issue is resolved for me as well.

**Comment by 1989gironimo** [comment]
I think, it's fixed now. Don't have this behavior anymore.
