### ISSUE TITLE
Cannot see UI in dark mode

### ISSUE THREAD

**Issue by helpfulBrother** [LedgerHQ/ledger-live-desktop#2733]
When loading Ledger Live I cannot see any of the UI elements, if I hover over an element I get the modal (see screenshot).

I can resolve this by reverting back to v 1.15.0 which does not have dark mode.

1. Where are the settings stored so I can remove/reset back to light mode.
2. Please let me know if you need any more info?

W10 Enterprise 1809
Build : 17763.1098

Thanks

![image](https://user-images.githubusercontent.com/44999712/77017477-593f8e80-69c6-11ea-9d1b-bb4dd1a6be5e.png)

**Comment by gre** [comment]
@helpfulBrother can you confirm it always happens when you start Ledger Live?
@IAmMorrow is this the bug that you potentially fix as part of https://github.com/LedgerHQ/ledger-live-desktop/pull/2730 ?

the result of this PR is available under this custom build if you want to confirm the bug would be fixed https://github.com/LedgerHQ/ledger-live-desktop/actions/runs/58236427 **but assume this build is not an official one, only to be used to test if the bug is solved.** we should ship that result in our next release (ETA 1-2 week from now)

**Comment by helpfulBrother** [comment]
Yeah it always happens when I start LL.

When the app first launches I see the spinning ledger logo, and then the underlying UI briefly (1/2 second) before everything looks like above.

I tried the build you linked and it fixes the issue.

Can I use that build until the fix is out, or should I revert to 1.15.0?

**Comment by gre** [comment]
It is a non-official build (a build in the middle of our development branch) so you may expect bugs, I would generally not recommend to use such build. (sometimes useful to quickly check a fix)

essentially consider it like a beta software / nightly. We generally prefer our users to use our production release. That fix will be delivered in our next release. You can still rollback to 1.20.0 (but beware if you used a password on your Ledger Live, you will have to **Reset** because going backward in version is not supported and the encryption changed from 1.x to 2.0).

Thanks a lot of confirming this bug is fixed, we're glad to here.
