### ISSUE TITLE
Ledger Live 2.1.0, 2.2.0, 2.2.3 Installers and Uninstallers for Windows are triggering Windows Defender with Trojan:Win32/Bulta!rfn detection

### ISSUE THREAD

**Issue by d-rez** [LedgerHQ/ledger-live-desktop#2822]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.1.0
- Platform and version: Win10

#### Expected behavior

Installer installs software

#### Actual behavior

Installer gets blocked by Windows Defender, 

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fBulta!rfn&threatid=2147694403

#### Steps to reproduce the behavior

* Download installer from [GitHub releases](https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v2.1.0), specifically the [Windows installer](https://github.com/LedgerHQ/ledger-live-desktop/releases/download/v2.1.0/ledger-live-desktop-2.1.0-win.exe)
* Launch the installer or go to a folder where it's downloaded to
* Windows Defender pop-up shows up, threat is marked as "serious" and the file gets deleted

![image](https://user-images.githubusercontent.com/1719659/78733215-2c104b80-7988-11ea-8620-a52fbee44083.png)

Note: 2.2.0 installer doesn't trigger this

**Comment by d-rez** [comment]
On top of that, more resources related to 2.2.0 installation get detected as a Trojan as well:

![image](https://user-images.githubusercontent.com/1719659/78953300-be952400-7b1b-11ea-8abe-adf1a97d8dca.png)

**Comment by gre** [comment]
our upcoming 2.2.3 should have this fixed.

**Comment by d-rez** [comment]
No worries, I know it's not a normal issue but depending on a platform that could possibly go into a full release unnoticed. Feel free to close once addressed :)

**Comment by picatextra** [comment]
Still detected with 2.2.3

**Comment by Dviros** [comment]
Can confirm Uninstaller.exe is still triggering Defender:
![image](https://user-images.githubusercontent.com/23431860/78997483-910da200-7b3e-11ea-9858-bc281973bdb1.png)

**Comment by ftapon** [comment]
![warning](https://user-images.githubusercontent.com/55924891/79398964-e5e25b80-7f36-11ea-8740-7e89ab72a8ad.jpg)
Same problem. 
According to the Ledger folks on Reddit, it's a false positive.

**Comment by gre** [comment]
we are working on it #2860

**Comment by asohbat** [comment]
after installing 2.2.3 , my windows immediately raised the flag for this trojan in the ledger uninstaller .exe
the problem became worse when i tried to uninstall ledger live , these files(screenshot) were made from A to Z when i finally uninstalled the program (i had to manually allow the uninstaller.exe in defender to run to be able to uninstall the program, i hope my windows is not infected , surely i wont connect my device to desktop until a solution comes up).
![Untitled](https://user-images.githubusercontent.com/45170538/79491902-620e9900-8034-11ea-9173-67141ca8a626.png)

**Comment by d-rez** [comment]
Bracing for a tide of newcomers commenting "me too"

**Comment by gre** [comment]
Yes the issue is due to https://github.com/electron-userland/electron-builder/issues/4793 that upgraded NSIS which likely is flagged by Windows antivirus.. (false positive)

The issue only affects the Uninstaller and in the meantime you can use https://github.com/LedgerHQ/ledger-live-desktop/releases/download/v2.2.3/Uninstall.Ledger.Live.exe if you want to uninstall Ledger Live. unfortunately you MUST uninstall Live if you installed a 2.2.3 from scratch because app updates won't update the Uninstaller.. only the first install of Ledger Live do.
so all users that have installed 2.2.3 for the first time need to uninstall it either by allowing the false positive virus detection or by using that separate uninstaller..

That's why we are now preparing a 2.2.4 to try to minimize number of users entering this problem. It's already a prerelease at the moment.

thanks

**Comment by gre** [comment]
2.2.4 was released. make sure to check message above. we'll try to document it better next week.

**Comment by d-rez** [comment]
Thanks! Glad that's sorted :) 

btw, 

> unfortunately you MUST uninstall Live if you installed a 2.2.3 from scratch because app updates won't update the Uninstaller.. only the first install of Ledger Live do.
so all users that have installed 2.2.3 for the first time need to uninstall it either by allowing the false positive virus detection or by using that separate uninstaller..

Are you sure that's the case? AV removed the uninstaller and when I installed 2.2.4 over my 2.2.3 install (which was missing the uninstaller due to above), the uninstaller got recreated just fine and the entry re-appeared in Windows' Add/Remove Apps

**Comment by gre** [comment]
very interesting! i guess it works if the uninstaller was removed before updating then 🤔  maybe it's just not copied if it exists. thanks for your feedback

**Comment by a1exandrovm** [comment]
Ledger Live Version Ver. 2.0.1, Ver. 2.2.3 on
Windows 7 & Windows 10 64-bit

360 Total Security detects the virus (Generic / Trojan.Downloader.251) in the installation file from your official site. Ledger Live Desktop Ver. 2.0.1, Ver. 2.2.3

On three devices I checked the distribution from your official site, and on all three devices with the pre-installed 360Total Security antivirus, I got a warning.

Additionally, I rechecked your file through the VirusTotal.com and MetaDefender.opswat.com online virus scan service (attached screenshot). This service also gives a warning, referring to the engine Qihoo-360 by 360 Total Security. Let me remind you that the previous Ledger Live distribution was installed without problems and without warnings.

Please close this bug so that users can safely install the Ledger Live application update for Windows. After all, the installation package The distribution of the previous version was installed well, without threats to the operating system.
![AlertLLD223](https://user-images.githubusercontent.com/21088677/79696974-a1352800-8288-11ea-8265-9e11aeb5c5bb.jpg)
![virustotal-alert-LLD2-2-3](https://user-images.githubusercontent.com/21088677/79696978-a2feeb80-8288-11ea-9eb5-73f4cfbe8640.JPG)
![virus in LLD2-2-3](https://user-images.githubusercontent.com/21088677/79696979-a2feeb80-8288-11ea-93f6-6ed627998e62.jpg)
![360 TS Detected Virus](https://user-images.githubusercontent.com/21088677/79696980-a3978200-8288-11ea-8d18-292d17663be8.jpg)
![virustotal](https://user-images.githubusercontent.com/21088677/79696981-a3978200-8288-11ea-983f-c42d4eab4988.jpg)

**Comment by gre** [comment]
The bug is closed and has been solved in 2.2.4. Just be aware you need to fully uninstall 2.2.3 if you had it installed in the first time to correctly recover from the antivirus detection situation.

Here is the diagram we think currently cover everything.

**The TLDR is that as soon as you have Ledger Live's Uninstaller being detected as a virus, we recommend to uninstall the Live using a "valid" (not detected as a virus) Uninstaller that we will also distribute on our website soon** (but it's going to be https://github.com/LedgerHQ/ledger-live-desktop/releases/download/v2.2.3/Uninstall.Ledger.Live.exe – sha256sum of 
0e7245dde4d656758c3f03724e1615239cbe358f1a61db0b3b6326669b5cbd60 )

![analysis_of_false_positive_uninstaller_issue](https://user-images.githubusercontent.com/211411/79751575-19e0c680-8313-11ea-8f5f-7f2da1c2a5c4.png)

**Comment by gre** [comment]
if there is any remaining issue you are facing and even after uninstalling and reinstalling completely, please create a new Github issue or contact our tech support. Thanks!
