### ISSUE TITLE
New App. Ledger Live Desktop Windows also contains the Trojan virus (Generic / Trojan.Downloader.251)

### ISSUE THREAD

**Issue by a1exandrovm** [LedgerHQ/ledger-live-desktop#2867]
#### Ledger Live Version Ver. 2.0.1, Ver. 2.2.3 on

 Windows 7 & Windows 10 64-bit

360 Total Security detects the virus (Generic / Trojan.Downloader.251) in the installation file from your official site. Ledger Live Desktop Ver. 2.0.1, Ver. 2.2.3

On three devices I checked the distribution from your official site, and on all three devices with the pre-installed 360Total Security antivirus, I got a warning.

Additionally, I rechecked your file through the VirusTotal.com and MetaDefender.opswat.com online virus scan service (attached screenshot). This service also gives a warning, referring to the engine Qihoo-360 by 360 Total Security. Let me remind you that the previous Ledger Live distribution was installed without problems and without warnings.

Please close this bug so that users can safely install the Ledger Live application update for Windows. After all, the installation package The distribution of the previous version was installed well, without threats to the operating system.
![virus in LLD2-2-3](https://user-images.githubusercontent.com/21088677/79696691-fa9c5780-8286-11ea-9af2-9508e92ee554.jpg)
![360 TS Detected Virus](https://user-images.githubusercontent.com/21088677/79696708-0f78eb00-8287-11ea-8df2-68afa1ac4bc0.jpg)
![virustotal-alert-LLD2-2-3](https://user-images.githubusercontent.com/21088677/79696781-6a124700-8287-11ea-8331-f3bb18e1db6f.JPG)
![AlertLLD223](https://user-images.githubusercontent.com/21088677/79696787-6f6f9180-8287-11ea-887d-95e8a3d75857.jpg)

**Comment by a1exandrovm** [comment]
Your new Ledger-live-desktop-2.2.4 application also contains a virus

![360ts](https://user-images.githubusercontent.com/21088677/79772582-e9ac1e80-8338-11ea-8eb7-bf95ce5d5d8f.jpg)
![virustotal-LLD-2-2-4](https://user-images.githubusercontent.com/21088677/79772586-eadd4b80-8338-11ea-97a2-d40b27ff6be9.jpg)

**Comment by sp1d3r** [comment]
It's a false-positive.

**Comment by a1exandrovm** [comment]
> Это ложноположительный. @sp1d3r 

Женя, да я понимаю, вопрос в другом. Это ведь серьёзный софт, могли бы доработать эту историю. Тем более в старых версиях таких ошибок нет. В конце концов другой упаковщик могут использовать. Ведь будут и другие пользователи, коллекционирующие криптовалюты в на свой леджер )

**Comment by gre** [comment]
it was fixed if you Uninstall your version and reinstall 2.3.0.

Please see https://github.com/LedgerHQ/ledger-live-desktop/issues/2822

**Comment by a1exandrovm** [comment]
> it was fixed if you Uninstall your version and reinstall 2.3.0.

 Sorry, @gre you're wrong.

The fact is that I have 3 laptops, and only one has the old version of Ledger Live Widows installed. By the way, it was installed without errors and additional warnings ...

Now, no matter on which laptop I am trying to download the distribution kit from the official Ledger site - My antivirus 360 Total Security displays a warning about the danger.

Including laptops on which Ledger products have never been installed before. Thus, it is impossible to remove and reinstall a non-existing program )

**Comment by a1exandrovm** [comment]
> it was fixed if you Uninstall your version and reinstall 2.3.0.
> 
> Please see #2822

Sorry, @gre you're wrong.

The fact is that I have 3 laptops, and only one has the old version of Ledger Live Widows installed. By the way, it was installed without errors and additional warnings ...

Now, no matter on which laptop I am trying to download the distribution kit from the official Ledger site - My antivirus 360 Total Security displays a warning about the danger.

Including laptops on which Ledger products have never been installed before. Thus, it is impossible to remove and reinstall a non-existing program )

**Comment by sp1d3r** [comment]
I have a bit mixed feelings about it. You have the point indeed, and I fully support your concern @a1exandrovm, tho I would like to share the similar story, which ended up with fix from AV side:

In the past I had problems when Kaspersky detected my software (to be concrete, one of the dependencies which was to hard and costly to rebuild) as Trojan (tho other AV solutions didn't) - but after working with the lab directly (analyzing the binary and reviewing the source code), I was able to prove that their check had flaw and they decided to fix _their_ check - and detections had stopped after virus signature updates.

While it indeed the concerning thing and may be fixed from Ledger side due to importance of the software (e.g. rolling back in case the root case of problem is in the dependency), giving that only 1/68 AV detected the issue, it likely the problem with AV check. AVs, even reputable, aren't ideal either (Microsoft already removed the false-positive detection rule which also detected trojan in the Ledger Uninstaller from their Defender product). I would ping also the 360 Total Security lab (like someone here pinged Microsoft) and try to trace the root cause of the issue - they may still use outdated signatures in their engine.
