### ISSUE TITLE
Disabling PIN code on startup

### ISSUE THREAD

**Issue by marekolszewski** [LedgerHQ/ledger-live-desktop#2892]
- [X] I have checked this feature was not yet requested.

Cosmos, Tezos, and Celo validators have corresponding apps to securely sign blocks using ledger nano devices. Unfortunately, these devices must be manually booted up so that the PIN can be entered before the device starts signing blocks. This is awkward for remote setups and makes it hard to recover from power outages or hangs, which has caused some validators to prefer YubiHSMs.

To mitigate against this, I would love to see an option that disables the PIN on starting up a ledger device. The setting could be enabled via Ledger Live in the developer settings area to make sure that only people who know what they are doing enable it.

Alternatively, it could be nice to support remote unlocking via USB, which would also solve the problem.

**Comment by gre** [comment]
Unfortunately this is not something that Ledger Live can do, it's a feature for the firmware. I'm not sure if we ever want to have this possible because it could be a threat to having users not using pin code and get their funds stolen if we unlock this possibility.

but it's not really for Ledger Live team to decide here, i would recommend you contact our team on Slack. https://join.slack.com/t/ledger-dev/shared_invite/zt-dqm7xn7a-5Pt5JaENO8ANpQEdj0L07w
