### ISSUE TITLE
Monero *READ ONLY* Feature on Ledger Live

### ISSUE THREAD

**Issue by neo4uo** [LedgerHQ/ledger-live-desktop#3025]
- [x] I have checked this feature was not yet requested.

#### Part of the application
As you know there is a READ ONLY wallet feature of Monero from their Wallet, I know that it would be almost impossible to add full Wallet feature to Ledger Live, but READ Only with using the public key seems possible. I do not know if this has been investigated already, but did not realise this until I ran across this feature with apps on the the Google Play Store.

Thanks

**Comment by Zaczero** [comment]
> READ Only with using the public key seems possible

Does it really? The whole point of Monero is that you can't see the balance nor transactions without the corresponding private key. Public key is only used for receiving transaction but in order to check if there is any transaction going into your wallet you have to perform some math with your private key on each new block in the blockchain.

### Did you rather mean the view key?

https://web.getmonero.org/resources/moneropedia/viewkey.html

This will allow you to see the incoming transaction but not the outgoing.  
"Therefore, the balance of a Monero address as shown via a viewkey should not be relied upon."

In my opinion this idea is not worth the effort. If you can't calculate the balance reliably then you won't display it in the portfolio. The only benefit would be displaying more incoming transactions in the transaction log. But still.. I think it's too much work for such a minor improvement. You will have to install the standalone Monero app anyways.
