### ISSUE TITLE
Add a DApp Browser to Ledger Live mobile

### ISSUE THREAD

**Issue by keilunDev** [LedgerHQ/ledger-live-desktop#3158]
Currently there is no solution to use a Ledger Nano X with DeFi applications on mobile. Recently, many wallets have integrated a dapp browser for mobile, but not a single one supports an hardware wallet (with the exception of the Algorand wallet, but it is not Ethereum compatible). This request is to enable Ledger Nano X users to fully use their wallet on mobility (especially on tablets).

**Comment by KipK** [comment]
I second that. For now Ledger is not usable with Defi apps.

**Comment by gre** [comment]
another possibility for this problem is to use Wallet Connect (so for us to support that protocol). We're looking at different possibility, but making an in app browser is complex to manage well and also can have issue regarding Apple ios app admission.
(btw mobile project is on https://github.com/LedgerHQ/ledger-live-mobile )

**Comment by nickyrabit** [comment]
this is risky though

**Comment by Awzaw** [comment]
It's great that we now have WalletConnect, but it really needs to support other chains, especially BSC, FTM and MATIC. Some Dapps work using the Ethereum app, but most fail with the error "can't switch network", or just don't connect at all. Hoping well eventually get a proper Dapps browser in LL supporting multiple networks!
