### ISSUE TITLE
spike on the first day of each month on the yearly view

### ISSUE THREAD

**Issue by rocketflames** [LedgerHQ/ledger-live-desktop#3250]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.14.0** (but this bug has been present for many versions)
- Platform and version: **Windows 10**

#### Expected behavior

Portfolio and account graphs should be accurate.

#### Actual behavior

There is a **random spike on the first day of each month** on the **yearly** view, that does not reflect historical asset performance at all. This spike appears on the first few days of each and every month except the current one.

This happens both in Ledger Live Desktop and official Android app.

#### Steps to reproduce the behavior

Just switch to the portfolio or an asset and display countervalues in a national currency (USD, EUR, ...)

![image](https://user-images.githubusercontent.com/73272171/96830237-9ff8d980-142a-11eb-8a6d-d771a1497118.png)

**Comment by gre** [comment]
Hello, we are aware of this issue and to solve this we have completely reworked the countervalues (as part of other problems we had with them). We have opened a beta testing program in order to know if our rework fully works for you, we invite users that want join the beta to follow instruction available in https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/2.16.0-countervalues-beta-0

**Comment by rocketflames** [comment]
Hello,
Thanks but I'd rather not fill in 15 pages of personal information just to access a testfix.
If it is not completely ready to be enabled by default, maybe you could make it a switch in the next official update?

**Comment by rocketflames** [comment]
Hello,
The issue is still present on Ledger Live 2.17.1 :

![image](https://user-images.githubusercontent.com/73272171/100255782-e1096f80-2f3b-11eb-8966-9ddb8bb6737a.png)

**Comment by gre** [comment]
Will be fixed in 2.18.0
