### ISSUE TITLE
Tezos KT1 subaccount is shown but it is not managed by account

### ISSUE THREAD

**Issue by denver-s** [LedgerHQ/ledger-live-desktop#3254]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.1.4 (and before)
- Platform and version: Windows 10

#### Expected behavior

Under "Accounts" section, show only KT1 smart contracts managed by the tz1 account of the Ledger user.

#### Actual behavior

Under "Accounts" section, it is shown a subaccount (a KT1 smart contract) which is not managed by the "main" tz1 account. It is just a KT1 contract that, when it was originated, it has specified a delegate (my tz1 account).

#### Steps to reproduce the behavior

- Originate a KT1 smart contract giving a delegate since origination (something like `originate contract <new> transferring <qty> from <src> running <prg> --delegate <address>`).
- Open Ledger Live as the `<address>` manager.
- Ledger Live shows it as a subaccount of `<address>`.

**Comment by denver-s** [comment]
v2.15 might have fixed this, can anybody from Ledger confirm?

**Comment by gre** [comment]
We deprecate the support of KT account, you will have to use another wallet if you didn't migrate yet since the Babylon upgrade as it was recommended. You can still use older version of Ledger Live to do this or another wallet, but the support of KT account is going to be dropped as a legacy tech debt.
