### ISSUE TITLE
Uppercase letters instead of lowercase in ETH address

### ISSUE THREAD

**Issue by adomagala** [LedgerHQ/ledger-live-desktop#3328]
I have created ETH send to address 0x0ee8e0e6969a65fbe5e089ded9c291d0a4191f00 ([link](https://etherscan.io/tx/0xbf6532c6292631b4ca9759072aa0e95a6c7003a50dd7d94d547c4702a515e595)), but the application and ledger showed adres 0x0eE8e0E6969a65Fbe5e089DED9c291d0a4191f00. Fortunately, the transaction have been sended to corect adres.

#### Ledger Live Version

- Ledger Live 2.17.1

#### Part of the application to improve

Creating transaction

**Comment by gre** [comment]
Hi,

this behavior is related to [EIP 55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md). ( example of article that explain it: https://medium.com/exodus-movement/eip55-why-its-important-what-is-this-and-why-am-i-talking-about-it-now-ac9254f43bb6 )

The casing in ethereum is not important for the address (it's still the same account) however it's important to checksum and to add a small validation that you didn't had a typo somewhere in the address.

I am curious to know the place where you initially took the destination address that is in lowercase (is it an exchange, another wallet?) because to me the "bug" is more on their side. I invite you to contact them and request them to use EIP 55 because Ledger Live strongly encourages it. Even if you can still use a lower case address we also currently are displaying a yellow warning when you paste the recipient in order to advocate the usage of EIP 55.

For these reasons, we currently have no plan to change this behavior.

**Comment by adomagala** [comment]
Hi,

Yes, this accounts is an exchange.

Thanks you for help.
