### ISSUE TITLE
Ledger Live for MacOS crashes the operating system (Big Sur)

### ISSUE THREAD

**Issue by emx0r** [LedgerHQ/ledger-live-desktop#3418]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.19.0
- Platform and version: MacOS Big Sur 11.1

#### Actual behavior

After opening the app and trying to connect it with Ledger Nano device, it crashes the operating system.
Same problem happens also when trying to setup the connection to full node.

This problem was reported by multiple users on reddit.

#### Steps to reproduce the behavior

Open Ledger Live on Big Sur and connect with hw wallet

**Comment by emx0r** [comment]
This problem seems to be fixed after latest MacOS update

**Comment by gre** [comment]
Ok thanks. Indeed MacOS Big Sur had some instabilities. I'm glad to know it's now fixed. thanks

**Comment by SG-code-byte** [comment]
Hey there, my ledger live program on apple crashed today with the old version. apple just closed the program an I coun´t open since than. Has anyone an idea how to fix the problem? Should I deinstall the whole softeware and get the new Ledger Live 2.33.1 version. Could this work? 

Thank you for your advices.
