### ISSUE TITLE
EmphyCoin improperly detected price

### ISSUE THREAD

**Issue by moseslecce** [LedgerHQ/ledger-live-desktop#3447]
#### Ledger Live Version and Operating System

- tested on Ledger Live v2.19.0
- Platform and version: Mac 10.15.7

#### Expected behavior

The token should show up as the contract 0x50ee674689d75c0f88e8f83cfe8c4b69e8fd590d with price at the current time of $ 0.0264

#### Actual behavior

The token shows up with a price of $44.15 at the current time.

#### Steps to reproduce the behavior

Open Ledger Live with a wallet containing the coin (EPY) under contract 
https://etherscan.io/token/0x50Ee674689d75C0f88E8f83cfE8c4B69E8fd590D

*Note this is the link that opens when clicking the contract from within Ledger Live.

**Comment by 10686142** [comment]
I am having the same issue. Wouldn't it be better anyway to bring back the "Rate provider" option under settings? 
Because there is no way we can change it now. 

P.s. I also see that some other people are experiencing similar issue on this subreddit:
https://www.reddit.com/r/ledgerwallet/comments/k9iar3/2180_ledger_update_is_missing_rate_provider_for/

**Comment by cthepot-ledger** [comment]
Please try the latest version. If it does not solve your situation please contact support on support.ledger.com.
