### ISSUE TITLE
HoloToken and Uniswap not showing price  Showing  this -

### ISSUE THREAD

**Issue by mblanchette1003** [LedgerHQ/ledger-live-desktop#3458]
#### Ledger Live Version and Operating System

- tested on Ledger Live **version2.19.0**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 10.0.19042 Build

#### Actual behavior

 There is no total $ under accounts HoloToken and Uniswap in CA there is only a - compared to other coins I have

#### Steps to reproduce the behavior  alwasy there never seen price of these two coins

 go see the total and it doesn't change even after I cleared the cache

![IMG_1467](https://user-images.githubusercontent.com/36650584/104222041-bc942480-540f-11eb-96ff-335b1e743ae4.PNG)

**Comment by mblanchette1003** [comment]
Thanks for the update. Marc

**Comment by gre** [comment]
this will be fixed in our upcoming release, not 2.20.0 but **2.21.0**.

This is a never ending topics, there is always going to be more tokens and ticker changes, it's a general maintenance cycle, the "countervalue bugs" that are mentionned to be fixed are real bugs that impacted the whole consistency of countervalues, vs this topic is more a configuration to change for a specific token.

**Comment by mblanchette1003** [comment]
Thanks for the update
________________________________
