### ISSUE TITLE
development environment for mocking ledger device

### ISSUE THREAD

**Issue by dvwright** [LedgerHQ/ledger-live-desktop#3725]
Hi, apologies, this doesn't really belong here but I can't find a discord, chat or anywhere to speak to developers.

I'm wondering if there is a way to mock a ledger device for development purposes. Like even just to get past the 'verify your device', 'connect your device', etc. 

I have forked the code and set up my environment, is there a way to 'spoof' a Nano X for example for testing purposes? Or do you have to actually have the physical device?

Would having a development environment for ledger live setup have any effect on an installed official release version?

Thanks

**Comment by LFBarreto** [comment]
Hi! if you wish to launch the desktop app using mocks you can set the env variable in a .env file at the root of the project with 
```
MOCK=1
```
or running the app like so on your terminal
```
MOCK=1 yarn start
```

 using this will enable mock functionalities on all the app and you can even mock certain devices responses that would otherwise lock you on certain steps such as adding accounts or sending transactions.

Be aware that the mocks don't cover the full scope of the app just yet but it can help you unlock the main bulk of its features.

Once you started the app using mocks you should see on the bottom left corner a red box where you can trigger the different mock events that you might need.

Per instance to get past the onboarding pairing you need to select `listApps` then `result`

![localhost_8080_webpack_index html_theme=null](https://user-images.githubusercontent.com/11752937/114154511-c7802780-9920-11eb-84c6-b72c0c53cf7c.png)

**Comment by dvwright** [comment]
Fantastic! Thank you @LFBarreto

**Comment by dvwright** [comment]
Hi @LFBarreto How to I enable more assets in the app catalog? For example I'm trying to access Cosmos but it's not available. Is there a setting? (Sorry for all the questions I don't want to take up your time but I would like to get up and running, is there a better place to ask questions?) Thanks

**Comment by LFBarreto** [comment]
You can add any live supported currency mock account you want you simply need to follow the add new account flow for it.

You first will select the currency for which you want to add an account then normally you would need a real device but since you're in a mock environment you can mock device responses for it to work. in that case should also be `result`.

Once this step passed you should see 3 mock accounts for this currency created and ready to add and work with.
The mock device doesn't need to have the currency apps installed or anything like that. 

feel free to ask any other question don't worry :smile:
