### ISSUE TITLE
Unable to add accounts to Ledger Live

### ISSUE THREAD

**Issue by deltarod** [LedgerHQ/ledger-live-desktop#3964]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.29.0**
- Platform and version: **Kubuntu 20.10**

#### Expected behavior

An account is added

#### Actual behavior

It errors, prompting me to save the logs

#### Steps to reproduce the behavior

Add an account to a freshly updated Ledger X, which has previously not been used with this version but has had accounts added successfully from previous versions.

**Comment by deltarod** [comment]
Is there anything potentially sensitive in the log file which I have saved or can I just make a gist with it?

**Comment by gre** [comment]
What coins are you importing?
Don't use a public gist because logs contains your public address info. but you could locate the precise error.

maybe it would be best to go through our official ledger support otherwise.

**Comment by deltarod** [comment]
I was specifically trying to add/import an already existing ETH account. Not too worried about public addresses, so here is the gist: https://gist.github.com/deltarod/0053995bc073193d0b9716f75e2d97a6

**Comment by Primea1** [comment]
Similar issue that i reported. Cannot add ETH accounts without an error. If i revert back to version 2.7 everything works fine.

**Comment by gre** [comment]
@deltarod the error i'm seeing in this log is `cannot open device with path /dev/hidraw3"` which sounds like it could be related to USB troubleshooting to do. https://support.ledger.com/hc/en-us/articles/360019868977-Fix-USB-connection-issues-with-Ledger-Live

@Primea1 i'm not sure if your case is the same problem and we may need to dig with contacting customer support directly. I am aware of one bug we fixed in 2.30.0 about ETH synchronisation of accounts. I need to see more precisely what error we are talking about here.

**Comment by deltarod** [comment]
@gre the udev rules fixed it, thanks for the help! @Primea1 I'm closing this issue, if you are still having any problems open your own.
