### ISSUE TITLE
Spam/Scam token on Polygon shows in desktop: SSX

### ISSUE THREAD

**Issue by sudoforge** [LedgerHQ/ledger-live-desktop#4990]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.41.3**
- Platform and version: `Linux 5.17.8-arch1-1 x86_64`

#### Expected behavior

SSX is a scamdrop token that was airdropped to users on the Polygon network. I would expect it to be hidden in Ledger Live by default.

#### Actual behavior

The scamdrop SSX token is displayed by default. 

#### Steps to reproduce the behavior

1. Receive the scamdrop SSX token.
2. Look at your Polygon tokens Ledger Live.

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. Could you inform our official support at https://support.ledger.com/  🙏  Thanks

**Comment by sudoforge** [comment]
Can I ask why a technical issue such as this, which is related to the application that this repository houses the source code for, should be opened with customer support instead of in a technical forum such as GitHub Issues?

**Comment by gre** [comment]
We are currently rebooting the management of this project using a monorepo and with better strategy for github issues. The best chance to get the information forwarded to our team is currently via support, because actually Ledger Live itself is not where the tokens are managed. they come from another database that we use.
I'll forward the information on my side.
