### ISSUE TITLE
Wrong ethereum balance in portfolio

### ISSUE THREAD

**Issue by ChakTochi** [LedgerHQ/ledger-live-desktop#935]
#### Ledger Live Version and Operating System

- Ledger Live **version_here**
- Platform: **windows OR mac OR linux**

**Comment by gre** [comment]
@Chakib-fort  do you have more detail?

We are aware of these limitation and maybe you fall into one of these:

- if you have received ETH from a contract, it is not yet accounted in the balance calculation (nor in the list of operations). This is a limitation of our API that we should fix in the next months.
- If you broadcast a new transaction, there is a short period where you will see your balance jumpy a bit, because not all the nodes are in sync at the same time. (API problem too, should get fixed soon)

**Comment by Chakib-fort** [comment]
![image](https://user-images.githubusercontent.com/35197399/42447152-189320d4-8379-11e8-850a-513d6cca3f8d.png)
my address receive first transction in 23 may but the graph show that i have eth before that
and when i chose rate provider i get this (flat graph and i dont even have eth in that period)
![image](https://user-images.githubusercontent.com/35197399/42447316-b28876a8-8379-11e8-8a69-d97e554153c3.png)

**Comment by gre** [comment]
So basically I think it's a bug in our API , i'll add a API flag to it but as not linked to Ledger Live itself will be addressed by our explorer API team.
as mentioned ETH don't support coin receive from contract, etc.. so the balance calculation is definitely wrong today

**Comment by trulex** [comment]
Is this why my ETH balance is 0 in Ledger Live, while it is correct in Ledger Wallet Ethereum Chrome app? Thanks

**Comment by MichalBelobrad** [comment]
I have the same problem as @trulex, zero balance in ledger live, correct balance in Ledger Ethereum Wallet.. thanks god my hearth is in a good shape, phew

**Comment by PierrickGT** [comment]
I've got the same kind of problem by exchanging DAI for ETH on oasis.direct
The ETH I've received appears like they've always been on my account.

There's also a weird drop that corresponds to the first real ETH I've received on my Ledger.

<img width="1077" alt="capture d ecran 2018-12-17 a 21 35 09" src="https://user-images.githubusercontent.com/2401738/50114491-eab0d580-0244-11e9-9358-91fe9f9ef9b8.png">
