### ISSUE TITLE
Support for Stellar (XLM) accounts

### ISSUE THREAD

**Issue by nunoarruda** [LedgerHQ/ledger-live-desktop#936]
- [x] I have checked this feature was not yet requested.

#### Part of the application

Accounts

#### Description

There's already a Stellar app for the Ledger Nano S, now it would be handy if Ledger Live supported Stellar accounts:
<img width="748" alt="screen shot 2018-07-09 at 11 19 17" src="https://user-images.githubusercontent.com/1189149/42447604-fe1ace0a-8369-11e8-8484-3be8b5add17d.png">

**Comment by chrisplusplus** [comment]
I will be contributing to the development of adding Stellar to account management.  I could really use some stellar sneks to lend a hand!

**Comment by kingofsevens** [comment]
Where can I follow your work on it @chrisplusplus?

**Comment by sphinxc0re** [comment]
@chrisplusplus I would also like to see stellar integration in ledger live

**Comment by juan-cortes** [comment]
you guys know about my pr? there's ready a working o yegtatiom done, just wait a couple weeks for the guys to have time to get it merged

**Comment by gre** [comment]
Thanks for the issue.
We're unifying integration requests into [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560).

Please follow [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560) for updates on what will be the process.

**Comment by atreyyu** [comment]
I've just upgraded to the latest version firmware (1.4.2) and latest stellar app in ledger live. Since then, log in to stellar.org/account-viewer is not working anymore. The ledger option is greyed out.
The tutorial says that "browser support" should be on, however since the firmware upgrade there is no "browser support" anymore. Instead you can select hash signing  yes or no (no idea what that means, anyway, is not working with neither of the 2 choices).
After googling this issue I see that there is a lot of talk abou that on reddit and no solution (since this summer !?).
Any news/solutions on this thing ?
