### ISSUE TITLE
Support for NEO accounts

### ISSUE THREAD

**Issue by nunoarruda** [LedgerHQ/ledger-live-desktop#937]
- [x] I have checked this feature was not yet requested.

#### Part of the application

Accounts

#### Description

There's already a NEO app for the Ledger Nano S, now it would be handy if Ledger Live supported NEO accounts:
<img width="519" alt="screen shot 2018-07-09 at 11 26 55" src="https://user-images.githubusercontent.com/1189149/42447998-400e3936-836b-11e8-9bcd-5b4fed44cc22.png">

**Comment by benzo8** [comment]
Seconded. NEO is supported by the hardware, so why not the software?

**Comment by Ardakilic** [comment]
Was wondering the same. The support of this would be great indeed.

**Comment by gre** [comment]
NEO is currently maintained by community (you will need to use the NEO app). We are currently focusing Ledger Live on supporting Bitcoin & bitcoin derivated cryptocurrencies + Ethereum + Ripple and we still have things to improve and bug to fix and many subjects to work on. We don't have yet any ETA of NEO support inside Ledger Live but the app is open source so this might happen with community contribution, that's why this issue remains opened :)

thanks for your patience

**Comment by wichtigwicht** [comment]
Is there a way as a conventional user to support you in your work if you are not a developer? Like writing to the blockchain CEOs of the respective coins and asking them to work with Ledger to get it to Ledger Live faster.

**Comment by gre** [comment]
Thanks for the issue.
We're unifying integration requests into [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560).

Please follow [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560) for updates on what will be the process.

**Comment by Ardakilic** [comment]
@gre The roadmap on Trello board [refers](https://trello.com/c/v3rLhujF/111-how-to-request-a-feature-for-ledger-live) to add a feature request here, but this issue is closed, so what will happen to these closed issues in regards of #1560 , because e.g: NEO is not on "new bolos apps" list on Trello.

**Comment by gsmachado** [comment]
@gre I know that #1560 was created and some time passed by... 
But, asking specifically about NEO support on Ledger Live, what's missing? Can I help with something? Any hints on where to start digging into?
