### ISSUE TITLE
Pick a ETH or ETC wallet address when adding an account

### ISSUE THREAD

**Issue by thuongle88** [LedgerHQ/ledger-live-desktop#973]
- [x] I have checked this feature was not yet requested.

#### Part of the application
I want to pick a  ETH or ETC wallet address when adding an account

#### Description
Ledger has many ETH and ETC wallet addresses. When open with MyEtherWallet or ClassicEtherWallet, you can select the address available for use. But when opened with Ledger Live, we only have default address and can not change. Therefore we can not use the balance in other addresses

**Comment by Deozaan** [comment]
I'm not experiencing this.

I used MEW for multiple ETH addresses on my Ledger. When I first added an ETH account on Ledger Live, it showed me all of my accounts I'd used on MEW and asked if I wanted to import them all.

**Comment by gre** [comment]
Ledger Live will automatically scan accounts on different paths: it supports for you MEW paths and the new convention. For ETC, it will scan all: MEW ETH path, MEW ETC path, new convention.

The "new convention" i'm talking about here is BIP44. This is the universal way to derivate all cryptocurrencies address and we now follow it. This is what we use to "create a new account" and we don't want to allow "any arbitrary paths" (because let's say you create an address 10 indexes ahead of time, leaving empty blocks, it's not optimal to do this and won't be easy for us to know "when accounts stops").

I hope this make sense.
