### ISSUE TITLE
Insufficient Device Storage

### ISSUE THREAD

**Issue by kryptomaniac87** [LedgerHQ/ledger-live-desktop#989]
Ledger Live Version and Operating System

- Ledger Live: 1.0.1
- Platform: macOS

Expected behavior

Manager should be able to install more than 4 apps in the Ledger Nano S since the last firmware update.

Actual behavior

I got the "insufficient device storage" when installing new app into the Ledger Nano S.

**Comment by gre** [comment]
This is true but only for bitcoin variant. If you install only Bitcoin app, you can literally install all apps except ETH and XRP. but as soon as you have BTC + ETH and/or XRP, it's taking much more space.
We can't consistently tell how much space is avalable and this is a device technical restriction but I know there are improvement made in the field (and next firmwares might even improve this).

Closing the issue because this is a device limitation, nothing Ledger Live itself can do.
